name: pdf

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: tex to pdf
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add --no-cache make inkscape && \
            tlmgr update --self && \
            tlmgr install inter && \
            make pdf

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
